export const controls = [
    "author",
    "comment",
    "info",
    "publication",
    "foundation",
    "price",
    "reward",
    "score",
    "favorite",
    "country",
    "language",
    "shortName",
    "status",
    "terminated",
    "original",
]