export const loginPath = '/login'
export const registrationPath = '/registration'
export const userPath = '/user/:userId'
export const collectionPath = '/user/:userId/:collectionId'
export const itemPath = '/item/:itemId'
export const homePath = '/'
export const searchPath = '/search'
export const adminPath = '/admin'