export const loginPath = '/login'
export const registrationPath = '/registration'
export const userPath = '/user'
export const collectionPath = '/:collectionId'
export const itemPath = '/item/:itemId'
export const homePath = '/'